### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper-1** [ObelusFamily/Anythink-Market-o9iphflo#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by birukkebede11** [comment]
<img width="1474" alt="productNoImage" src="https://user-images.githubusercontent.com/61163684/204115640-8f1642e1-cb01-42f3-b4af-929dd380515f.png">

**Comment by birukkebede11** [comment]
<img width="1474" alt="productNoImage" src="https://user-images.githubusercontent.com/61163684/204115697-1d4a2583-a718-4646-89bf-21c11c47fa2c.png">
